### ISSUE TITLE
Using device_tracker instead of input_boolean

### ISSUE THREAD

**Issue by nephilic** [andrewjfreyer/monitor#138]
I already had a lot of automation setup around device_trackers and didn't want to switch to input_boolean, but I did want to use multiple pi zeros and occupancy_confidence... So I did some digging and found the undocumented service below that will allow you to use device_trackers with occupancy_confidence and multiple pi zeros. Just thought you might want to reference this in your doc for those looking for a similar solution. Thanks.

```
Example:
- alias: John Occupancy On
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.john_occupancy_confidence
      above: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: device_tracker.john_tile
	location_name: home

- alias: John Occupancy Off
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.john_occupancy_confidence
      below: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: device_tracker.john_tile
	location_name: not_home
```

Source: https://community.home-assistant.io/t/device-tracker-from-script/97295/7
