### ISSUE TITLE
Monitor not scanning ARRIVAL or DEPART

### ISSUE THREAD

**Issue by jcastro** [andrewjfreyer/monitor#185]
Hello!

I had monitor running for months now without problem. Today I updated to the latest version and I'm not able to manually trigger through MQTT the arrival or depart scans. 

In my case sending 'monitor/scan/depart' or 'monitor/scan/arrival' doesn't show anything in the monitor output. However doing a 'monitor/scan/update' I can see the output on how it tries to update to the latest version and restarts monitor. This means it's correctly connected to the MQTT server. 

Any idea on what's going on? Something that has changed in the last month that could make monitor to not work again without tweaking stuff?

Here's my HA configuration in case it helps

```yaml
- platform: mqtt
  state_topic: 'monitor/pi3/XX:7C:25:XX:75:B0'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'jonatanwatchmonitor'

# iPhone Jonatan
- platform: mqtt
  state_topic: 'monitor/pi3/XX:98:9D:XX:9D:68'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'jonataniphonemonitor'

# Occupancy sensor Jonatan
- platform: min_max
  name: "Jonatan Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.jonatanwatchmonitor
    - sensor.jonataniphonemonitor

## Rebeca
# Apple Watch Rebeca
- platform: mqtt
  state_topic: 'monitor/pi3/XX:0F:24:XX:47:8E'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'rebecawatchmonitor'

# iPhone Rebeca
- platform: mqtt
  state_topic: 'monitor/pi3/XX:53:AC:XX:3E:87'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'rebecaiphonemonitor'

# Occupancy sensor Rebeca
- platform: min_max
  name: "Rebeca Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.rebecawatchmonitor
    - sensor.rebecaiphonemonitor

## House Occupancy
- platform: min_max
  name: "Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.jonatanwatchmonitor
    - sensor.jonataniphonemonitor
    - sensor.rebecawatchmonitor
    - sensor.rebecaiphonemonitor`

```
Thanks a lot!

*Edited to format codeblocks.*
