### ISSUE TITLE
Official docker image?

### ISSUE THREAD

**Issue by ammmze** [andrewjfreyer/monitor#190]
Do you have any interest in getting an official docker image in here? I'm new to this project, but I prefer to run everything in small docker containers. I've spent the last couple days figuring out getting this thing running in an alpine docker image. I've got it setup to build on a few different architectures (amd64, arm v6, arm v7, and arm 64). I'm gonna be running this on a Raspberry Pi Zero W, which is arm v6 and I can verify that it works on there (except for `bluetoothctl`...for whatever reason I can't seem to get that working, but it doesn't seem critical to the function of monitor.sh). 

If there is interest in this, I can put a PR together for it. We'd then need to get you set up with free account with travis-ci (or if you have another preferred ci service we can probably figure out the build on there) to automate the builds anytime you push to master (or beta).

https://github.com/mashupmill/docker-presence-monitor

I also came across a few things while working on this...
* It seems the expected location of the `.public_name_cache` file is inconsistent...in some areas its looking in the `base_directory` (which i'm mounting as `/config` in the docker container) and in other areas its looking for it in the current working directory (which is `/monitor` in the docker container)
* There is still a call to `systemctl` which doesn't exist in alpine. It's harmless other than causes an error output

**Comment by andrewjfreyer** [comment]
Good report, I'll think on this!

**Comment by vamichael** [comment]
I’ve only deployed through docker-hub before.  Any chance you can hook me up with a docker-compose.yml for the RPI Zero W?  I too prefer using containers.  It’s a way of life.

**Comment by ammmze** [comment]
Here's relevant part of my docker-compose ...

```yaml
version: '2.4'
services:
  monitor:
    container_name: monitor
    image: mashupmill/presence-monitor:latest-armv6
    network_mode: host
    privileged: true
    restart: unless-stopped
    command: ['-b']
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MQTT_ADDRESS: 192.168.0.10
      MQTT_USER: mqtt
      MQTT_PASSWORD: "***********"
      KNOWN_BEACON_ADDRESSES: |
        FF:FF:FF:FF:FF:FF Red Tag
        FF:FF:FF:FF:FF:FF Green Tag
        FF:FF:FF:FF:FF:FF White Tag
        FF:FF:FF:FF:FF:FF Black Tag
      KNOWN_STATIC_ADDRESSES: |
        FF:FF:FF:FF:FF:FF Alpha Phone BT
        FF:FF:FF:FF:FF:FF Beta Phone BT
```

Though I will warn that I haven't found it to be very stable yet. After a few days the process seems to hang. When I jump into the container, I find that there are some zombie processes that don't seem to get cleaned up. And my attempt at adding a health check (in addition to adding an 'autoheal' container) to re-create the container didn't work. Right now my attempt at a health check is to basically listen to the `main_pipe` which is where all the various things that are running writes messages to which are then picked up by the main process. I then write out a timestamp each time a message is received in the `main_pipe` and the health check basically just checks that we've received a message within the last N seconds. So it seems that even when the process hangs, there are still some things still writing to the `main_pipe`. 

The other idea I had for a health check is to listen for the online status message that gets pumped out every so often and basically do the same thing...so if we haven't received an online message in the last N seconds from when the health check runs, then we would consider it unhealthy.

But all-in-all the health check is just a bandaid until I can figure out why the process ends up hanging after a few days.
