### ISSUE TITLE
Suggested improvement to Home Assistant device_tracker.see automation example

### ISSUE THREAD

**Issue by airdrummingfool** [andrewjfreyer/monitor#242]
Right now in the section on using the `device_tracker` platform in HA, there are two automation scripts shown to update the `device_tracker` entity (one for "home", one for "not_home"). Using `data_template` in the action, this can be simplified to one automation for both "home" and "not_home" states:

```
- alias: "Update Andrew Device Tracker from BLE"
  trigger:
    - platform: state
      entity_id: sensor.andrew_occupancy_confidence
  action:
    - service: device_tracker.see
      data:
        dev_id: andrew
        source_type: bluetooth
      data_template:
        location_name: "{% if states('sensor. andrew_occupancy_confidence') | float > 10 %}home{% else %}not_home{% endif %}"
```

Thanks for this awesome project!

**Comment by anisite** [comment]
Thank for idea! @airdrummingfool I've added homeassistant start event to prevent bad indication after HA reboot 👍 

```
- alias: "Update Andrew Device Tracker from BT"
  trigger:
  - entity_id: sensor.andrew_occupancy_confidence
    platform: state
  - event: start
    platform: homeassistant
  action:
  - data:
      dev_id: andrew
      source_type: bluetooth
    data_template:
      location_name: '{% if states(''sensor.andrew_occupancy_confidence'') | float > 10 %}home{%
        else %}not_home{% endif %}'
    service: device_tracker.see
```
