### ISSUE TITLE
Unknown sensor values and Pi0 drops connection

### ISSUE THREAD

**Issue by Okosotthon** [andrewjfreyer/monitor#348]
Hello,

I have a marginal problem. (Hassio 0.117.1)
The created mqtt sensor showing Unknown state.
My mqtt topic is this : monitor/Pi0/peterphone, it receives the message correctly within the mqtt integration.

Received message inside mqtt integration:

```
{"id":"00:EC:0A:7D:C5:E3","confidence":"100","name":"
Peterphone ","manufacturer":"Xiaomi Communications Co Ltd","type":"KNOWN_MAC","retained":"false","timestamp":"Sat Oct 31 2020 08:51:11 GMT+0000 (GMT)","version":"0.2.200"}
```
My sensor config:

```
sensor:
  - platform: mqtt
    state_topic: 'monitor/Pi0/peterphone'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Pi0'
```
And by the way my Pi zero stops measuring (or I’m noob) after a while. I’m using monitor.sh -tadr, I would like to track my phone and tell wich room is in it, but it is not reporting after a few minutes even if I turn off my bluetooth it does not show confidence drop.
