### ISSUE TITLE
Q: How do I trigger a scan on all my ZeroW's after home assistant (re)start?

### ISSUE THREAD

**Issue by Bram1nat0r** [andrewjfreyer/monitor#39]
First of all : Love your solution! It's giving me so much more reliability to my presence detection!

I would like to have a scan triggered after I restart my Hass instance, because my monitor instances don't detect me for quite a while after a Hass restart.

My topic path = location

```
- id: trigger_scan
  alias: Trigger Scan
  hide_entity: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: 'location/scan/arrive'
        payload: '?????'
```

I have scanned my MQTT broker , and I got this message when I triggered monitor.sh -tr from the command-line :

location/scan/arrive
{"identity":"meterkast"}

But after re-publishing the same message to the broker, my known devices weren't scanned.

Thanks!
