### ISSUE TITLE
Change topic pad for arrive/depart trigger

### ISSUE THREAD

**Issue by gieljnssns** [andrewjfreyer/monitor#42]
Since I still have problems with an iPhone 6s loosing connection at night...
I've made a sensor for arrive/depart:
```
- platform: mqtt
  state_topic: 'monitor/scan/arrive'
  value_template: '{{ value_json.identity }}'
  expire_after: 60
  name: Mqtt Aankomst
```
And I made 2 triggers from HA
```
  mqqt_arrive_trigger:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: monitor/scan/arrive
          payload: "{'identity':'HA'}"
```
I want to change the topic path where the nodes are listening to/sending out, for depart or arrive scans.
So I can let HA decide to send the topic to the nodes
Node send ```monitor/scan/should_arrive_trigger``` -> Ha send ```monitor/scan/arrive```
