### ISSUE TITLE
I cant make the addon to work

### ISSUE THREAD

**Issue by jmsblah** [andrewjfreyer/monitor#427]
```
mqtt:
  broker: 127.0.0.1
  port: 1883
  username: "!secret mqtt_username"
  password: "!secret mqtt_password"
  topic_root: presence
  publisher: ""
known:
  beacons: []
  static:
    - XX:XX:XX:XX:XX:XX 
blacklist: []
extra_arguments: "-E"
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Bluetooth Presence Monitor
 Passive Bluetooth presence detection of beacons, cell phones, and other Bluetooth devices.
-----------------------------------------------------------
 Add-on version: 1.0.0
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 10.3  (amd64 / generic-x86-64)
 Home Assistant version: 2023.6.1
 Supervisor version: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] monitor.sh: executing... 
[19:17:44] INFO: Updating running configuration...
[cont-init.d] monitor.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:17:44] INFO: Starting required services...
Starting system message bus: dbus.
Starting bluetooth: bluetoothd.
[19:17:44] INFO: Updating Bluetooth Presence Monitor to latest version...
From https://github.com/andrewjfreyer/monitor
 + 87d433b...10b6cb7 master     -> origin/master  (forced update)
Previous HEAD position was 87d433b Merge pull request #289 from hmmbob/patch-1
HEAD is now at 10b6cb7 update intallation instructions
Already up to date.
[19:17:49] INFO: Starting Bluetooth Presence Monitor...
> updated monitor (v. Unknown) -> (v. 0.2.200)...
> using custom config directory [/opt/monitor]
> publishing MQTT .../scan/[arrival|depart]/[start|end]
using /opt/monitor as config dir
```
