### ISSUE TITLE
Also retain the monitor/......../status topic

### ISSUE THREAD

**Issue by gieljnssns** [andrewjfreyer/monitor#47]
I use 
```
- platform: mqtt
  state_topic: 'monitor/Garage/D0:2B:20:xxxxxxxxx'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'gPhone garage'
  availability_topic: "monitor/Garage/status"
  payload_available: "online"
  payload_not_available: "offline"
  json_attributes:
    - id
    - name
    - rssi
    - version
    - manufacturer
    - type
    - timestamp
    - retained
    - confidence
```
as my MQTT sensor but when I restart Hass, all MQTT sensors are unavailable because the availability_topic isn't retained, so I have to restart al monitor services.
Btw I use the -x flag
