### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by firestrife23** [andrewjfreyer/monitor#76]
Thank you for your monitor script and a valuable addition to my home assistant setup. Whenever I reboot home assistant, the information is lost unless I restart monitor script to republish MQTT message to provide the data to home assistant. I'm not fond of the retained message, and I'm wondering would it be possible for your script to republish the last known state after reconnecting to MQTT server?

**Comment by JerryWorkman** [comment]
I use ansible to restart my two monitor Pis when HA starts.

**Comment by firestrife23** [comment]
That's interesting, never worked with ansible before.

**Comment by Hertizch** [comment]
Try out the `monitor/scan/restart` command.

**Comment by firestrife23** [comment]
Thank you @Hertizch and that was helpful. Here's snippet of code from my automation for those who are interested.

```
- alias: Reboot BLE Monitors 
  trigger:
    event: start
    platform: homeassistant
  action:
    - service: mqtt.publish
      data:
        topic: monitor/scan/restart
```
