### ISSUE TITLE
dbus[70]: arguments to dbus_connection_get_object_path_data() were incorrect

### ISSUE THREAD

**Issue by Sjeff** [andrewjfreyer/monitor#79]
Running Intel NUC Docker Configuration.

After i updated to latest beta i receive the following error.

Looks like everything is working as is should be.
Thought i would be good to report this error anyway.
 
```
dbus[70]: arguments to dbus_connection_get_object_path_data() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 5904.

This is normally a bug in some application using the D-Bus library.

   D-Bus not built with -rdynamic so unable to print a backtrace
> XX:XX:XX:XX:XX:XX has not previously connected to hci0
> XX:XX:XX:XX:XX:XX will publish updates to: monitor/home/XX:XX:XX:XX:XX:XX
> YY:YY:YY:YY:YY:YY has not previously connected to hci0
> YY:YY:YY:YY:YY:YY will publish updates to: monitor/home/YY:YY:YY:YY:YY:YY
```

**Comment by andrewjfreyer** [comment]
Appreciate the report, but since docker isn't the default method for running this script (although it may be in the future), I'll go ahead and close this. Please follow up if you notice anything negative happening. 

Thanks!

**Comment by hatemzidi** [comment]
i know that this issue is closed but i managed to fix the bluetooth problem under docker.

i'm using
- Intel NUC NUC7CJYH
- Debian stretch with kernel 4.19.0-0.bpo.1-amd64
- docker v.18.09.1, build 4c52b90

i managed to create an image using this Docker file:
```
FROM debian:stretch-slim

RUN set -x && \
    apt-get update && \
    apt-get install -y  --no-install-recommends \
        bash \
        bc \
        bluez \
        bluez-hcidump \
        bluetooth \
#        usbutils \ #if you are using an external usb stick
        ca-certificates \
        curl \
        git \
        mosquitto-clients

RUN mkdir /monitor && \
    git clone https://github.com/andrewjfreyer/monitor.git /monitor

VOLUME ["/monitor", "/config"]

# Set up the entry point script and default command
COPY run.sh /
RUN chmod +x /run.sh
ENTRYPOINT ["/run.sh"]

WORKDIR /monitor

CMD ["/bin/bash", "monitor.sh", "-D", "/config"]
```

the run.sh file
```
#!/bin/bash
set -e

# inspired from https://github.com/moby/moby/issues/16208#issuecomment-161770118
service dbus start
service bluetooth start
hciconfig hci0 up

exec "$@"
```
my docker-compose.
```
version: '3'

services:
  monitor.sh:
#    build:
#       context: /PATH/TO/YOUR/DOCKERFILE
    image: hatemzidi/monitor.sh:v0.1.981
    container_name: monitor.sh-test
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/monitor/config:/config
    network_mode: host
    privileged: true
    command: bash monitor.sh -x -a -D /config
```

just run ```docker-compose up```, configure your monitor properly and rerun it.
et voilà :)

**Comment by andrewjfreyer** [comment]
Thanks for the follow-up!

**Comment by Sjeff** [comment]
@hatemzidi do you have a working dockerfile with mosquitto 1.5+ for the latest monitor update?

**Comment by hatemzidi** [comment]
@Sjeff since i'm using mosquitto with other services, i just added it in my docker-compose as a separate service and linked monitor with mosquitto.

**Comment by Sjeff** [comment]
@hatemzidi can you share the docker-compose file?
i'm running mosquitto in a separate container already.

**Comment by hatemzidi** [comment]
@Sjeff 
here is a snippet of my docker-compose
```
version: '3'

services:
#[...]
  monitor.sh:
    image: hatemzidi/monitor.sh:v0.2.053
    container_name: monitor.sh
    restart: always
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/dbus:/run/dbus
      - /etc/localtime:/etc/localtime:ro
      - ./config/monitor:/config
    privileged: true
    cap_add:
      - NET_ADMIN
    command: bash monitor.sh -x -a -D /config

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883/tcp"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mosquitto/settings:/mosquitto/config
      - mosquitto-data:/mosquitto/data

#[...]

```
since monitor is in host mode, i call the mosquitto using the loopback (localhost:1883)
